<!DOCTYPE html>
<html>
    <head>
        <title>Error</title>
        <link rel="stylesheet" type="text/css" href="/css/screen.css" />
        <script type="text/javascript" src="/js/main.js"></script>
    </head>
    <body>
        <h1><?= $error ?></h1>
        <?= ( $this->message ? "<pre>{$this->message}</pre>" : null ) ?>
        <?= ( $this->trace ? "<pre>{$this->trace}</pre>" : null ) ?>
    </body>
</html>


