<?php 
use Helper\Html;
use Helper\LayoutPart; ?>
<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!--> <html lang="en" class="no-js"> <!--<![endif]-->
<!-- BEGIN HEAD -->
<head>
    <meta charset="utf-8" />
    <title><?php echo (isset($this->meta_title) ? $this->meta_title : 'OMS--51页游事业部资源控制平台');?></title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1.0" name="viewport" />
    <meta content="" name="description" />
    <meta content="" name="author" />
    <meta name="MobileOptimized" content="320">
    <!-- BEGIN GLOBAL MANDATORY STYLES -->          
    <link href="<?=$this->assets_base_url;?>/assets/plugins/font-awesome/css/font-awesome.min.css<?=$this->resource_version;?>" rel="stylesheet" type="text/css"/>
    <link href="<?=$this->assets_base_url;?>/assets/plugins/bootstrap/css/bootstrap.min.css<?=$this->resource_version;?>" rel="stylesheet" type="text/css"/>
    <link href="<?=$this->assets_base_url;?>/assets/plugins/uniform/css/uniform.default.css<?=$this->resource_version;?>" rel="stylesheet" type="text/css"/>
    <!-- END GLOBAL MANDATORY STYLES -->
    <!-- BEGIN PAGE LEVEL STYLES -->
    <link rel="stylesheet" type="text/css" href="<?=$this->assets_base_url;?>/assets/plugins/select2/select2_metro.css<?=$this->resource_version;?>" />
    <?php echo $this->css ?>
    <?php echo Html::placeHolder()->appendLink();?>
    <?php echo Html::placeHolder()->appendStyle();?>
    <!-- END PAGE LEVEL STYLES -->
    <!-- BEGIN THEME STYLES --> 
    <link href="<?=$this->assets_base_url;?>/assets/css/style-metronic.css<?=$this->resource_version;?>" rel="stylesheet" type="text/css"/>
    <link href="<?=$this->assets_base_url;?>/assets/css/style.css<?=$this->resource_version;?>" rel="stylesheet" type="text/css"/>
    <link href="<?=$this->assets_base_url;?>/assets/css/style-responsive.css<?=$this->resource_version;?>" rel="stylesheet" type="text/css"/>
    <link href="<?=$this->assets_base_url;?>/assets/css/plugins.css<?=$this->resource_version;?>" rel="stylesheet" type="text/css"/>
    <link href="<?=$this->assets_base_url;?>/assets/css/themes/default.css<?=$this->resource_version;?>" rel="stylesheet" type="text/css" id="style_color"/>
    <link href="<?=$this->assets_base_url;?>/assets/css/custom.css<?=$this->resource_version;?>" rel="stylesheet" type="text/css"/>
    <!-- END THEME STYLES -->
    <link rel="shortcut icon" href="favicon.ico" />
</head>
<!-- END HEAD -->
<!-- BEGIN BODY -->
<body class="page-header-fixed page-full-width">
    <!-- BEGIN HEADER -->   
    <div class="header navbar navbar-inverse navbar-fixed-top">
        <!-- BEGIN TOP NAVIGATION BAR -->
        <div class="header-inner">
            <!-- BEGIN LOGO -->  
            <a class="navbar-brand" href="index.html">
            <img src="<?php $this->assets_base_url;?>/assets/img/logo.png" alt="logo" class="img-responsive" />
            </a>
            <!-- END LOGO -->
            <div class="hor-menu hidden-sm hidden-xs">
                <ul class="nav navbar-nav">
                    <?php echo LayoutPart::drawHeaderNavMenu($this->header_nav);?>
                </ul>
            </div>
            <!-- BEGIN RESPONSIVE MENU TOGGLER --> 
            <a href="javascript:;" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <img src="<?php $this->assets_base_url;?>/assets/img/menu-toggler.png" alt="" />
            </a> 
            <!-- END RESPONSIVE MENU TOGGLER -->
            <!-- BEGIN TOP NAVIGATION MENU -->
            <ul class="nav navbar-nav pull-right">
                <li class="dropdown user">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
                    <img alt="" src="<?php $this->assets_base_url;?>/assets/img/avatar1_small.jpg"/>
                    <span class="username">Bob Nilson</span>
                    <i class="fa fa-angle-down"></i>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="extra_profile.html"><i class="fa fa-user"></i> My Profile</a></li>
                        <li><a href="page_calendar.html"><i class="fa fa-calendar"></i> My Calendar</a></li>
                        <li><a href="inbox.html"><i class="fa fa-envelope"></i> My Inbox <span class="badge badge-danger">3</span></a></li>
                        <li><a href="#"><i class="fa fa-tasks"></i> My Tasks <span class="badge badge-success">7</span></a></li>
                        <li class="divider"></li>
                        <li><a href="javascript:;" id="trigger_fullscreen"><i class="fa fa-move"></i> Full Screen</a></li>
                        <li><a href="extra_lock.html"><i class="fa fa-lock"></i> Lock Screen</a></li>
                        <li><a href="login.html"><i class="fa fa-key"></i> Log Out</a></li>
                    </ul>
                </li>
                <!-- END USER LOGIN DROPDOWN -->
            </ul>
            <!-- END TOP NAVIGATION MENU -->
        </div>
        <!-- END TOP NAVIGATION BAR -->
    </div>
    <!-- END HEADER -->
    <div class="clearfix"></div>
    <!-- BEGIN CONTAINER -->
    <div class="page-container">
        <!-- BEGIN EMPTY PAGE SIDEBAR -->
        <div class="page-sidebar navbar-collapse collapse">
            <ul class="page-sidebar-menu visible-sm visible-xs">
                <?php echo LayoutPart::drawHeaderNavSidebar($this->header_nav);?>
            </ul>
        </div>
        <!-- END EMPTY PAGE SIDEBAR -->
        <!-- BEGIN PAGE -->
        <div class="page-content">
            <!-- END BEGIN STYLE CUSTOMIZER --> 
            <div class="row">
                <div class="col-md-12">
                <?php echo $content ?>
                </div>
                <!-- HERE WILL BE LOADED AN AJAX CONTENT -->
            </div>
        </div>
        <!-- BEGIN PAGE -->     
    </div>
    <!-- END CONTAINER -->
    <!-- BEGIN FOOTER -->
    <div class="footer">
        <div class="footer-inner">
            2013 &copy; 51webgame@51.com.
        </div>
        <div class="footer-tools">
            <span class="go-top">
            <i class="fa fa-angle-up"></i>
            </span>
        </div>
    </div>
    <!-- END FOOTER -->
    <!-- BEGIN JAVASCRIPTS(Load javascripts at bottom, this will reduce page load time) -->
    <!-- BEGIN CORE PLUGINS -->   
    <!--[if lt IE 9]>
    <script src="<?=$this->assets_base_url;?>/assets/plugins/respond.min.js<?=$this->resource_version?>"></script>
    <script src="<?=$this->assets_base_url;?>/assets/plugins/excanvas.min.js<?=$this->resource_version?>"></script> 
    <![endif]-->   
    <script src="<?=$this->assets_base_url;?>/assets/plugins/jquery-1.10.2.min.js<?=$this->resource_version?>" type="text/javascript"></script>
    <script src="<?=$this->assets_base_url;?>/assets/plugins/jquery-migrate-1.2.1.min.js<?=$this->resource_version?>" type="text/javascript"></script>
    <!-- IMPORTANT! Load jquery-ui-1.10.3.custom.min.js<?=$this->resource_version?> before bootstrap.min.js<?=$this->resource_version?> to fix bootstrap tooltip conflict with jquery ui tooltip -->
    <script src="<?=$this->assets_base_url;?>/assets/plugins/jquery-ui/jquery-ui-1.10.3.custom.min.js<?=$this->resource_version?>" type="text/javascript"></script>      
    <script src="<?=$this->assets_base_url;?>/assets/plugins/bootstrap/js/bootstrap.min.js<?=$this->resource_version?>" type="text/javascript"></script>
    <script src="<?=$this->assets_base_url;?>/assets/plugins/bootstrap-hover-dropdown/twitter-bootstrap-hover-dropdown.min.js<?=$this->resource_version?>" type="text/javascript" ></script>
    <script src="<?=$this->assets_base_url;?>/assets/plugins/jquery-slimscroll/jquery.slimscroll.min.js<?=$this->resource_version?>" type="text/javascript"></script>
    <script src="<?=$this->assets_base_url;?>/assets/plugins/jquery.blockui.min.js<?=$this->resource_version?>" type="text/javascript"></script>  
    <script src="<?=$this->assets_base_url;?>/assets/plugins/jquery.cookie.min.js<?=$this->resource_version?>" type="text/javascript"></script>
    <script src="<?=$this->assets_base_url;?>/assets/plugins/uniform/jquery.uniform.min.js<?=$this->resource_version?>" type="text/javascript" ></script>
    <!-- END CORE PLUGINS -->
    <script type="text/javascript" src="<?=$this->assets_base_url;?>/assets/plugins/select2/select2.min.js<?=$this->resource_version?>"></script>
    <script src="<?=$this->assets_base_url;?>/assets/scripts/app.js<?=$this->resource_version?>"></script>
    <?php echo $this->javascripts ?>
    <?php echo Html::placeHolder()->appendScript();?>
    <script>
    jQuery(document).ready(function() {    
       // initiate layout and plugins
       App.init();
    });
</script>
    <!-- END JAVASCRIPTS -->
</body>
<!-- END BODY -->
</html>