<div class="row">
	<div class="col-md-12">
		<div class="tabbable tabbable-custom boxless">
			<ul class="nav nav-tabs">
				<li class="active"><a href="#tab_0" data-toggle="tab">服务器静态信息录入</a></li>
				<li><a href="#tab_1" data-toggle="tab">服务器静态信息配置添加</a></li>
				<li><a  href="#tab_2" data-toggle="tab">2 Columns Horizontal</a></li>
				<li><a href="#tab_3" data-toggle="tab">2 Columns View Only</a></li>
				<li><a  href="#tab_4" data-toggle="tab">Row Seperated</a></li>
				<li><a  href="#tab_5" data-toggle="tab">Bordered</a></li>
				<li><a  href="#tab_6" data-toggle="tab">Row Stripped</a></li>
				<li><a  href="#tab_7" data-toggle="tab">Label Stripped</a></li>
			</ul>
			<div class="tab-content">
				<div class="tab-pane active" id="tab_0">
					<div class="portlet box purple">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-cogs"></i>服务器信息录入
				</div>
				<div class="tools">
					<a href="javascript:;" class="expand"></a>
				</div>
			</div>
			<div class="portlet-body">
				<table class="table table-hover">
					<thead>
					</thead>
					<tbody>
						<tr>
							<td>内网ip:</td>
							<td><input type="text" id="inner_ip" name="inner_ip" class="form-control input-medium"></input></td>
							<td>外网ip:</td>
							<td><input type="text" id="out_ip" name="out_ip" class="form-control input-medium"></input></td>
						</tr>
						<tr>
							<td>cpu:</td>
							<td><input type="text" id="cpu" name="cpu" class="form-control input-medium"></input></td>
							<td>内存:</td>
							<td><input type="text" id="mem" name="mem" class="form-control input-medium"></input></td>
						</tr>
						<tr>
							<td>硬盘:</td>
							<td><input type="text" id="disk" name="disk" class="form-control input-medium"></input></td>
							<td>IDC:</td>
							<td><input type="text" id="idc" name="idc" class="form-control input-medium"></input></td>
						</tr>
						<tr>
							<td>机柜:</td>
							<td><input type="text" id="cabinet" name="cabinet" class="form-control input-medium"></input></td>
							<td>型号:</td>
							<td><input type="text" id="model" name="model" class="form-control input-medium"></input></td>
						</tr>
						<tr>
							<td>负责人:</td>
							<td><input type="text" id="supervisor" name="supervisor" class="form-control input-medium"></input>
							</td>
						</tr>
						<tr>
							<td>用途:</td>
							<td>
								<select id="app" name="app" class="form-control input-medium select2me" data-placeholder="Select...">
									<option value="1">宁波电信服务器</option>
									<option value="2">宁波网通服务器</option>
									<option value="3">宁波电信数据库</option>
									<option value="4">宁波网通数据库</option>
									<option value="5">鲁谷BGP服务器</option>
									<option value="6">鲁谷BGP数据库</option>
									<option value="7">宁波电信公共服务器</option>
									<option value="8">宁波网通公共服务器</option>
									<option value="9">鲁谷BGP公共服务器</option>
									<option value="10">办公机房</option>
								</select>
							</td>
							<td>状态:</td>
							<td>
								<select id="status" name="status" class="form-control input-medium select2me" data-placeholder="Select...">
									<option value="1">在线</option>
									<option value="2">闲置</option>
									<option value="3">待升级</option>
									<option value="4">待下架</option>
									<option value="5">已下架</option>
								</select>
							</td>
						</tr>
						<tr>
							<td>启用时间:</td>
							<td>
								<input id="datepickerFrom" name="datepickerFrom" class="form-control form-control-inline input-medium date-picker" data-date-format="yyyy-mm-dd" size="16" type="text" value="" />
							</td>
							<td>备注:</td>
							<td><input type="text" id="remark" name="remark" class="form-control input-medium"></input></td>
						</tr>
						<tr>
							<td>硬件产权:</td>
							<td>
								<select id="property_right" name="property_right" class="form-control input-medium select2me" data-placeholder="Select...">
									<option value="1">公司自有</option>
									<option value="2">租用</option>
								</select>
							</td>
							<td></td>
							<td><input type="button" id="remark" onclick="saveData();" class="btn btn-success" value="确定"></input></td>
						</tr>
					</tbody>
				</table>
			</div>
		</div>
		
				</div>
				<div class="tab-pane" id="tab_1">
					<div class="portlet box green">
						<div class="portlet-title">
							<div class="caption"><i class="fa fa-reorder"></i>Form Actions On Bottom</div>
							<div class="tools">
								<a href="javascript:;" class="collapse"></a>
								<a href="#portlet-config" data-toggle="modal" class="config"></a>
								<a href="javascript:;" class="reload"></a>
								<a href="javascript:;" class="remove"></a>
							</div>
						</div>
						<div class="portlet-body form">
							<!-- BEGIN FORM-->
							<form action="#" class="form-horizontal">
								<div class="form-body">
									<div class="form-group">
										<label  class="col-md-3 control-label">配置类型</label>
										<div class="col-md-4">
											<select id="property_right" name="property_right" class="form-control input-medium select2me" data-placeholder="Select...">
												<option value="cpu">cpu</option>
												<option value="mem">内存</option>
												<option value="disk">硬盘</option>
												<option value="id才">IDC</option>
												<option value="cabinet">机柜</option>
												<option value="model">型号</option>
												<option value="supervisor">负责人</option>
												<option value="status">状态</option>
											</select>
										</div>
									</div>
									<div class="form-group">
										<label  class="col-md-3 control-label">内容，以回车分隔</label>
										<div class="col-md-9">
											<div class="input-group">
												<textarea class="form_control" row="3" style="margin: 0px; width: 545px; height: 160px;"></textarea>
											</div>
										</div>
									</div>
								</div>
								<div class="form-actions fluid">
									<div class="col-md-offset-3 col-md-9">
										<button type="submit" class="btn blue">Submit</button>
										<button type="button" class="btn default">Cancel</button>                              
									</div>
								</div>
							</form>
							<!-- END FORM--> 
						</div>
					</div>
				</div>
				<div class="tab-pane " id="tab_2">
					<div class="portlet box green">
						<div class="portlet-title">
							<div class="caption"><i class="fa fa-reorder"></i>Form Sample</div>
							<div class="tools">
								<a href="javascript:;" class="collapse"></a>
								<a href="#portlet-config" data-toggle="modal" class="config"></a>
								<a href="javascript:;" class="reload"></a>
								<a href="javascript:;" class="remove"></a>
							</div>
						</div>
						<div class="portlet-body form">
							<!-- BEGIN FORM-->
							<form action="#" class="form-horizontal">
								<div class="form-body">
									<h3 class="form-section">Person Info</h3>
									<div class="row">
										<div class="col-md-6">
											<div class="form-group">
												<label class="control-label col-md-3">First Name</label>
												<div class="col-md-9">
													<input type="text" class="form-control" placeholder="Chee Kin">
													<span class="help-block">This is inline help</span>
												</div>
											</div>
										</div>
										<!--/span-->
										<div class="col-md-6">
											<div class="form-group has-error">
												<label class="control-label col-md-3">Last Name</label>
												<div class="col-md-9">
													<select name="foo" class="select2me form-control">
														<option value="1">Abc</option>
														<option value="1">Abc</option>
														<option value="1">This is a really long value that breaks the fluid design for a select2</option>
													</select>
													<span class="help-block">This field has error.</span>
												</div>
											</div>
										</div>
										<!--/span-->
									</div>
									<!--/row-->
									<div class="row">
										<div class="col-md-6">
											<div class="form-group">
												<label class="control-label col-md-3">First Name</label>
												<div class="col-md-9">
													<input type="text" class="form-control" placeholder="Chee Kin">
													<span class="help-block">This is inline help</span>
												</div>
											</div>
										</div>
										<!--/span-->
										<div class="col-md-6">
											<div class="form-group has-error">
												<label class="control-label col-md-3">Last Name</label>
												<div class="col-md-9">
													<input type="text" class="form-control" placeholder="Lim">
													<span class="help-block">This field has error.</span>
												</div>
											</div>
										</div>
										<!--/span-->
									</div>
									<!--/row-->
									<div class="row">
										<div class="col-md-6">
											<div class="form-group">
												<label class="control-label col-md-3">Gender</label>
												<div class="col-md-9">
													<select class="form-control">
														<option value="">Male</option>
														<option value="">Female</option>
													</select>
													<span class="help-block">Select your gender.</span>
												</div>
											</div>
										</div>
										<!--/span-->
										<div class="col-md-6">
											<div class="form-group">
												<label class="control-label col-md-3">Date of Birth</label>
												<div class="col-md-9">
													<input type="text" class="form-control" placeholder="dd/mm/yyyy">
												</div>
											</div>
										</div>
										<!--/span-->
									</div>
									<!--/row-->        
									<div class="row">
										<div class="col-md-6">
											<div class="form-group">
												<label class="control-label col-md-3">Category</label>
												<div class="col-md-9">
													<select class="select2_category form-control"  data-placeholder="Choose a Category" tabindex="1">
														<option value="Category 1">Category 1</option>
														<option value="Category 2">Category 2</option>
														<option value="Category 3">Category 5</option>
														<option value="Category 4">Category 4</option>
													</select>
												</div>
											</div>
										</div>
										<!--/span-->
										<div class="col-md-6">
											<div class="form-group">
												<label class="control-label col-md-3">Membership</label>
												<div class="col-md-9">
													<div class="radio-list">                                                
														<label class="radio-inline">
														<input type="radio" name="optionsRadios2" value="option1" />
														Free
														</label>
														<label class="radio-inline">
														<input type="radio" name="optionsRadios2" value="option2" checked />
														Professional
														</label>  
													</div>
												</div>
											</div>
										</div>
										<!--/span-->
									</div>
									<h3 class="form-section">Address</h3>
									<!--/row-->                   
									<div class="row">
										<div class="col-md-6">
											<div class="form-group">
												<label class="control-label col-md-3">Address 1</label>
												<div class="col-md-9">
													<input type="text" class="form-control" >
												</div>
											</div>
										</div>
										<div class="col-md-6">
											<div class="form-group">
												<label class="control-label col-md-3">Address 2</label>
												<div class="col-md-9">
													<input type="text" class="form-control" >
												</div>
											</div>
										</div>
									</div>
									<div class="row">
										<div class="col-md-6">
											<div class="form-group">
												<label class="control-label col-md-3">City</label>
												<div class="col-md-9">
													<input type="text" class="form-control"> 
												</div>
											</div>
										</div>
										<!--/span-->
										<div class="col-md-6">
											<div class="form-group">
												<label class="control-label col-md-3">State</label>
												<div class="col-md-9">
													<input type="text"  class="form-control"> 
												</div>
											</div>
										</div>
										<!--/span-->
									</div>
									<!--/row-->           
									<div class="row">
										<div class="col-md-6">
											<div class="form-group">
												<label class="control-label col-md-3">Post Code</label>
												<div class="col-md-9">
													<input type="text" class="form-control"> 
												</div>
											</div>
										</div>
										<!--/span-->
										<div class="col-md-6">
											<div class="form-group">
												<label class="control-label col-md-3">Country</label>
												<div class="col-md-9">
													<select class="form-control">
														<option>Country 1</option>
														<option>Country 2</option>
													</select>
												</div>
											</div>
										</div>
										<!--/span-->
									</div>
									<!--/row-->
								</div>
								<div class="form-actions fluid">
									<div class="row">
										<div class="col-md-6">
											<div class="col-md-offset-3 col-md-9">
												<button type="submit" class="btn green">Submit</button>
												<button type="button" class="btn default">Cancel</button>                              
											</div>
										</div>
										<div class="col-md-6"></div>
									</div>
								</div>
							</form>
							<!-- END FORM-->                
						</div>
					</div>
				</div>
				<div class="tab-pane " id="tab_3">
					<div class="portlet box blue">
						<div class="portlet-title">
							<div class="caption"><i class="fa fa-reorder"></i>Form Sample</div>
							<div class="tools">
								<a href="javascript:;" class="collapse"></a>
								<a href="#portlet-config" data-toggle="modal" class="config"></a>
								<a href="javascript:;" class="reload"></a>
								<a href="javascript:;" class="remove"></a>
							</div>
						</div>
						<div class="portlet-body form">
							<!-- BEGIN FORM-->
							<form class="form-horizontal" role="form">
								<div class="form-body">
									<h2 class="margin-bottom-20"> View User Info - Bob Nilson </h2>
									<h3 class="form-section">Person Info</h3>
									<div class="row">
										<div class="col-md-6">
											<div class="form-group">
												<label class="control-label col-md-3">First Name:</label>
												<div class="col-md-9">
													<p class="form-control-static">Bob</p>
												</div>
											</div>
										</div>
										<!--/span-->
										<div class="col-md-6">
											<div class="form-group">
												<label class="control-label col-md-3">Last Name:</label>
												<div class="col-md-9">
													<p class="form-control-static">Nilson</p>
												</div>
											</div>
										</div>
										<!--/span-->
									</div>
									<!--/row-->
									<div class="row">
										<div class="col-md-6">
											<div class="form-group">
												<label class="control-label col-md-3">Gender:</label>
												<div class="col-md-9">
													<p class="form-control-static">Male</p>
												</div>
											</div>
										</div>
										<!--/span-->
										<div class="col-md-6">
											<div class="form-group">
												<label class="control-label col-md-3">Date of Birth:</label>
												<div class="col-md-9">
													<p class="form-control-static">20.01.1984</p>
												</div>
											</div>
										</div>
										<!--/span-->
									</div>
									<!--/row-->        
									<div class="row">
										<div class="col-md-6">
											<div class="form-group">
												<label class="control-label col-md-3">Category:</label>
												<div class="col-md-9">
													<p class="form-control-static">Category1</p>
												</div>
											</div>
										</div>
										<!--/span-->
										<div class="col-md-6">
											<div class="form-group">
												<label class="control-label col-md-3">Membership:</label>
												<div class="col-md-9">
													<p class="form-control-static">Free</p>
												</div>
											</div>
										</div>
										<!--/span-->
									</div>
									<!--/row-->                
									<h3 class="form-section">Address</h3>
									<div class="row">
										<div class="col-md-6">
											<div class="form-group">
												<label class="control-label col-md-3">Address:</label>
												<div class="col-md-9">
													<p class="form-control-static">#24 Sun Park Avenue, Rolton Str</p>
												</div>
											</div>
										</div>
									</div>
									<div class="row">
										<div class="col-md-6">
											<div class="form-group">
												<label class="control-label col-md-3">City:</label>
												<div class="col-md-9">
													<p class="form-control-static">New York</p>
												</div>
											</div>
										</div>
										<!--/span-->
										<div class="col-md-6">
											<div class="form-group">
												<label class="control-label col-md-3">State:</label>
												<div class="col-md-9">
													<p class="form-control-static">New York</p>
												</div>
											</div>
										</div>
										<!--/span-->
									</div>
									<!--/row-->           
									<div class="row">
										<div class="col-md-6">
											<div class="form-group">
												<label class="control-label col-md-3">Post Code:</label>
												<div class="col-md-9">
													<p class="form-control-static">457890</p>
												</div>
											</div>
										</div>
										<!--/span-->
										<div class="col-md-6">
											<div class="form-group">
												<label class="control-label col-md-3">Country:</label>
												<div class="col-md-9">
													<p class="form-control-static">USA</p>
												</div>
											</div>
										</div>
										<!--/span-->
									</div>
								</div>
								<div class="form-actions fluid">
									<div class="row">
										<div class="col-md-6">
											<div class="col-md-offset-3 col-md-9">
												<button type="submit" class="btn green"><i class="fa fa-pencil"></i> Edit</button>
												<button type="button" class="btn default">Cancel</button>                              
											</div>
										</div>
										<div class="col-md-6"></div>
									</div>
								</div>
							</form>
							<!-- END FORM-->  
						</div>
					</div>
				</div>
				<div class="tab-pane"  id="tab_4">
					<div class="portlet box blue">
						<div class="portlet-title">
							<div class="caption"><i class="fa fa-reorder"></i>Form Sample</div>
							<div class="tools">
								<a href="javascript:;" class="collapse"></a>
								<a href="#portlet-config" data-toggle="modal" class="config"></a>
								<a href="javascript:;" class="reload"></a>
								<a href="javascript:;" class="remove"></a>
							</div>
						</div>
						<div class="portlet-body form">
							<!-- BEGIN FORM-->
							<form action="#" class="form-horizontal form-row-seperated">
								<div class="form-body">
									<div class="form-group">
										<label class="control-label col-md-3">First Name</label>
										<div class="col-md-9">
											<input type="text" placeholder="small" class="form-control" />
											<span class="help-block">This is inline help</span>
										</div>
									</div>
									<div class="form-group">
										<label class="control-label col-md-3">Last Name</label>
										<div class="col-md-9">
											<input type="text" placeholder="medium" class="form-control" />
											<span class="help-block">This is inline help</span>
										</div>
									</div>
									<div class="form-group">
										<label class="control-label col-md-3">Gender</label>
										<div class="col-md-9">
											<select  class="form-control">
												<option value="">Male</option>
												<option value="">Female</option>
											</select>
											<span class="help-block">Select your gender.</span>
										</div>
									</div>
									<div class="form-group">
										<label class="control-label col-md-3">Date of Birth</label>
										<div class="col-md-9">
											<input type="text" class="form-control"  placeholder="dd/mm/yyyy">
										</div>
									</div>
									<div class="form-group">
										<label class="control-label col-md-3">Category</label>
										<div class="col-md-9">
											<select class="form-control select2_category">
												<option value="Category 1">Category 1</option>
												<option value="Category 2">Category 2</option>
												<option value="Category 3">Category 5</option>
												<option value="Category 4">Category 4</option>
											</select>
										</div>
									</div>
									<div class="form-group">
										<label class="control-label col-md-3">Multi-Value Select</label>
										<div class="col-md-9">
											<select class="form-control select2_sample1" multiple>
												<optgroup label="NFC EAST">
													<option>Dallas Cowboys</option>
													<option>New York Giants</option>
													<option>Philadelphia Eagles</option>
													<option>Washington Redskins</option>
												</optgroup>
												<optgroup label="NFC NORTH">
													<option>Chicago Bears</option>
													<option>Detroit Lions</option>
													<option>Green Bay Packers</option>
													<option>Minnesota Vikings</option>
												</optgroup>
												<optgroup label="NFC SOUTH">
													<option>Atlanta Falcons</option>
													<option>Carolina Panthers</option>
													<option>New Orleans Saints</option>
													<option>Tampa Bay Buccaneers</option>
												</optgroup>
												<optgroup label="NFC WEST">
													<option>Arizona Cardinals</option>
													<option>St. Louis Rams</option>
													<option>San Francisco 49ers</option>
													<option>Seattle Seahawks</option>
												</optgroup>
												<optgroup label="AFC EAST">
													<option>Buffalo Bills</option>
													<option>Miami Dolphins</option>
													<option>New England Patriots</option>
													<option>New York Jets</option>
												</optgroup>
												<optgroup label="AFC NORTH">
													<option>Baltimore Ravens</option>
													<option>Cincinnati Bengals</option>
													<option>Cleveland Browns</option>
													<option>Pittsburgh Steelers</option>
												</optgroup>
												<optgroup label="AFC SOUTH">
													<option>Houston Texans</option>
													<option>Indianapolis Colts</option>
													<option>Jacksonville Jaguars</option>
													<option>Tennessee Titans</option>
												</optgroup>
												<optgroup label="AFC WEST">
													<option>Denver Broncos</option>
													<option>Kansas City Chiefs</option>
													<option>Oakland Raiders</option>
													<option>San Diego Chargers</option>
												</optgroup>
											</select>
										</div>
									</div>
									<div class="form-group">
										<label class="control-label col-md-3">Loading Data</label>
										<div class="col-md-9">
											<input type="hidden" class="form-control select2_sample2">
										</div>
									</div>
									<div class="form-group">
										<label class="control-label col-md-3">Tags Support List</label>
										<div class="col-md-9">
											<input type="hidden" class="form-control select2_sample3" value="red, blue">
										</div>
									</div>
									<div class="form-group">
										<label class="control-label col-md-3">Membership</label>
										<div class="col-md-9">
											<div class="radio-list">                                                
												<label>
												<input type="radio" name="optionsRadios2" value="option1" />
												Free
												</label>
												<label>
												<input type="radio" name="optionsRadios2" value="option2" checked />
												Professional
												</label>  
											</div>
										</div>
									</div>
									<div class="form-group">
										<label class="control-label col-md-3">Street</label>
										<div class="col-md-9">
											<input type="text" class="form-control" >
										</div>
									</div>
									<div class="form-group">
										<label class="control-label col-md-3">City</label>
										<div class="col-md-9">
											<input type="text"  class="form-control"> 
										</div>
									</div>
									<div class="form-group">
										<label class="control-label col-md-3">State</label>
										<div class="col-md-9">
											<input type="text"  class="form-control"> 
										</div>
									</div>
									<div class="form-group">
										<label class="control-label col-md-3">Post Code</label>
										<div class="col-md-9">
											<input type="text" class="form-control"> 
										</div>
									</div>
									<div class="form-group last">
										<label class="control-label col-md-3">Country</label>
										<div class="col-md-9">
											<select  class="form-control"></select>
										</div>
									</div>
								</div>
								<div class="form-actions fluid">
									<div class="row">
										<div class="col-md-12">
											<div class="col-md-offset-3 col-md-9">
												<button type="submit" class="btn green"><i class="fa fa-pencil"></i> Edit</button>
												<button type="button" class="btn default">Cancel</button>                              
											</div>
										</div>
									</div>
								</div>
							</form>
							<!-- END FORM-->  
						</div>
					</div>
				</div>
				<div class="tab-pane"  id="tab_5">
					<div class="portlet box blue ">
						<div class="portlet-title">
							<div class="caption"><i class="fa fa-reorder"></i>Form Sample</div>
							<div class="tools">
								<a href="javascript:;" class="collapse"></a>
								<a href="#portlet-config" data-toggle="modal" class="config"></a>
								<a href="javascript:;" class="reload"></a>
								<a href="javascript:;" class="remove"></a>
							</div>
						</div>
						<div class="portlet-body form">
							<!-- BEGIN FORM-->
							<form action="#" class="form-horizontal form-bordered">
								<div class="form-body">
									<div class="form-group">
										<label class="control-label col-md-3">First Name</label>
										<div class="col-md-9">
											<input type="text" placeholder="small" class="form-control" />
											<span class="help-block">This is inline help</span>
										</div>
									</div>
									<div class="form-group">
										<label class="control-label col-md-3">Last Name</label>
										<div class="col-md-9">
											<input type="text" placeholder="medium" class="form-control" />
											<span class="help-block">This is inline help</span>
										</div>
									</div>
									<div class="form-group">
										<label class="control-label col-md-3">Gender</label>
										<div class="col-md-9">
											<select  class="form-control">
												<option value="">Male</option>
												<option value="">Female</option>
											</select>
											<span class="help-block">Select your gender.</span>
										</div>
									</div>
									<div class="form-group">
										<label class="control-label col-md-3">Date of Birth</label>
										<div class="col-md-9">
											<input type="text" class="form-control"  placeholder="dd/mm/yyyy">
										</div>
									</div>
									<div class="form-group">
										<label class="control-label col-md-3">Category</label>
										<div class="col-md-9">
											<select class="form-control select2_category">
												<option value="Category 1">Category 1</option>
												<option value="Category 2">Category 2</option>
												<option value="Category 3">Category 5</option>
												<option value="Category 4">Category 4</option>
											</select>
										</div>
									</div>
									<div class="form-group">
										<label class="control-label col-md-3">Multi-Value Select</label>
										<div class="col-md-9">
											<select class="form-control select2_sample1" multiple>
												<optgroup label="NFC EAST">
													<option>Dallas Cowboys</option>
													<option>New York Giants</option>
													<option>Philadelphia Eagles</option>
													<option>Washington Redskins</option>
												</optgroup>
												<optgroup label="NFC NORTH">
													<option>Chicago Bears</option>
													<option>Detroit Lions</option>
													<option>Green Bay Packers</option>
													<option>Minnesota Vikings</option>
												</optgroup>
												<optgroup label="NFC SOUTH">
													<option>Atlanta Falcons</option>
													<option>Carolina Panthers</option>
													<option>New Orleans Saints</option>
													<option>Tampa Bay Buccaneers</option>
												</optgroup>
												<optgroup label="NFC WEST">
													<option>Arizona Cardinals</option>
													<option>St. Louis Rams</option>
													<option>San Francisco 49ers</option>
													<option>Seattle Seahawks</option>
												</optgroup>
												<optgroup label="AFC EAST">
													<option>Buffalo Bills</option>
													<option>Miami Dolphins</option>
													<option>New England Patriots</option>
													<option>New York Jets</option>
												</optgroup>
												<optgroup label="AFC NORTH">
													<option>Baltimore Ravens</option>
													<option>Cincinnati Bengals</option>
													<option>Cleveland Browns</option>
													<option>Pittsburgh Steelers</option>
												</optgroup>
												<optgroup label="AFC SOUTH">
													<option>Houston Texans</option>
													<option>Indianapolis Colts</option>
													<option>Jacksonville Jaguars</option>
													<option>Tennessee Titans</option>
												</optgroup>
												<optgroup label="AFC WEST">
													<option>Denver Broncos</option>
													<option>Kansas City Chiefs</option>
													<option>Oakland Raiders</option>
													<option>San Diego Chargers</option>
												</optgroup>
											</select>
										</div>
									</div>
									<div class="form-group">
										<label class="control-label col-md-3">Loading Data</label>
										<div class="col-md-9">
											<input type="hidden" class="form-control select2_sample2">
										</div>
									</div>
									<div class="form-group">
										<label class="control-label col-md-3">Tags Support List</label>
										<div class="col-md-9">
											<input type="hidden" class="form-control select2_sample3" value="red, blue">
										</div>
									</div>
									<div class="form-group">
										<label class="control-label col-md-3">Membership</label>
										<div class="col-md-9">
											<div class="radio-list">                                                
												<label>
												<input type="radio" name="optionsRadios2" value="option1" />
												Free
												</label>
												<label>
												<input type="radio" name="optionsRadios2" value="option2" checked />
												Professional
												</label>  
											</div>
										</div>
									</div>
									<div class="form-group">
										<label class="control-label col-md-3">Street</label>
										<div class="col-md-9">
											<input type="text" class="form-control" >
										</div>
									</div>
									<div class="form-group">
										<label class="control-label col-md-3">City</label>
										<div class="col-md-9">
											<input type="text"  class="form-control"> 
										</div>
									</div>
									<div class="form-group">
										<label class="control-label col-md-3">State</label>
										<div class="col-md-9">
											<input type="text"  class="form-control"> 
										</div>
									</div>
									<div class="form-group">
										<label class="control-label col-md-3">Post Code</label>
										<div class="col-md-9">
											<input type="text" class="form-control"> 
										</div>
									</div>
									<div class="form-group last">
										<label class="control-label col-md-3">Country</label>
										<div class="col-md-9">
											<select  class="form-control"></select>
										</div>
									</div>
								</div>
								<div class="form-actions fluid">
									<div class="row">
										<div class="col-md-12">
											<div class="col-md-offset-3 col-md-9">
												<button type="submit" class="btn green"><i class="fa fa-check"></i> Submit</button>
												<button type="button" class="btn default">Cancel</button>                              
											</div>
										</div>
									</div>
								</div>
							</form>
							<!-- END FORM-->  
						</div>
					</div>
				</div>
				<div class="tab-pane"  id="tab_6">
					<div class="portlet box blue ">
						<div class="portlet-title">
							<div class="caption"><i class="fa fa-reorder"></i>Form Sample</div>
							<div class="tools">
								<a href="javascript:;" class="collapse"></a>
								<a href="#portlet-config" data-toggle="modal" class="config"></a>
								<a href="javascript:;" class="reload"></a>
								<a href="javascript:;" class="remove"></a>
							</div>
						</div>
						<div class="portlet-body form">
							<!-- BEGIN FORM-->
							<form action="#" class="form-horizontal form-bordered form-row-stripped">
								<div class="form-body">
									<div class="form-group">
										<label class="control-label col-md-3">First Name</label>
										<div class="col-md-9">
											<input type="text" placeholder="small" class="form-control" />
											<span class="help-block">This is inline help</span>
										</div>
									</div>
									<div class="form-group">
										<label class="control-label col-md-3">Last Name</label>
										<div class="col-md-9">
											<input type="text" placeholder="medium" class="form-control" />
											<span class="help-block">This is inline help</span>
										</div>
									</div>
									<div class="form-group">
										<label class="control-label col-md-3">Gender</label>
										<div class="col-md-9">
											<select  class="form-control">
												<option value="">Male</option>
												<option value="">Female</option>
											</select>
											<span class="help-block">Select your gender.</span>
										</div>
									</div>
									<div class="form-group">
										<label class="control-label col-md-3">Date of Birth</label>
										<div class="col-md-9">
											<input type="text" class="form-control"  placeholder="dd/mm/yyyy">
										</div>
									</div>
									<div class="form-group">
										<label class="control-label col-md-3">Category</label>
										<div class="col-md-9">
											<select class="form-control select2_category">
												<option value="Category 1">Category 1</option>
												<option value="Category 2">Category 2</option>
												<option value="Category 3">Category 5</option>
												<option value="Category 4">Category 4</option>
											</select>
										</div>
									</div>
									<div class="form-group">
										<label class="control-label col-md-3">Multi-Value Select</label>
										<div class="col-md-9">
											<select class="form-control select2_sample1" multiple>
												<optgroup label="NFC EAST">
													<option>Dallas Cowboys</option>
													<option>New York Giants</option>
													<option>Philadelphia Eagles</option>
													<option>Washington Redskins</option>
												</optgroup>
												<optgroup label="NFC NORTH">
													<option>Chicago Bears</option>
													<option>Detroit Lions</option>
													<option>Green Bay Packers</option>
													<option>Minnesota Vikings</option>
												</optgroup>
												<optgroup label="NFC SOUTH">
													<option>Atlanta Falcons</option>
													<option>Carolina Panthers</option>
													<option>New Orleans Saints</option>
													<option>Tampa Bay Buccaneers</option>
												</optgroup>
												<optgroup label="NFC WEST">
													<option>Arizona Cardinals</option>
													<option>St. Louis Rams</option>
													<option>San Francisco 49ers</option>
													<option>Seattle Seahawks</option>
												</optgroup>
												<optgroup label="AFC EAST">
													<option>Buffalo Bills</option>
													<option>Miami Dolphins</option>
													<option>New England Patriots</option>
													<option>New York Jets</option>
												</optgroup>
												<optgroup label="AFC NORTH">
													<option>Baltimore Ravens</option>
													<option>Cincinnati Bengals</option>
													<option>Cleveland Browns</option>
													<option>Pittsburgh Steelers</option>
												</optgroup>
												<optgroup label="AFC SOUTH">
													<option>Houston Texans</option>
													<option>Indianapolis Colts</option>
													<option>Jacksonville Jaguars</option>
													<option>Tennessee Titans</option>
												</optgroup>
												<optgroup label="AFC WEST">
													<option>Denver Broncos</option>
													<option>Kansas City Chiefs</option>
													<option>Oakland Raiders</option>
													<option>San Diego Chargers</option>
												</optgroup>
											</select>
										</div>
									</div>
									<div class="form-group">
										<label class="control-label col-md-3">Loading Data</label>
										<div class="col-md-9">
											<input type="hidden" class="form-control select2_sample2">
										</div>
									</div>
									<div class="form-group">
										<label class="control-label col-md-3">Tags Support List</label>
										<div class="col-md-9">
											<input type="hidden" class="form-control select2_sample3" value="red, blue">
										</div>
									</div>
									<div class="form-group">
										<label class="control-label col-md-3">Membership</label>
										<div class="col-md-9">
											<div class="radio-list">                                              
												<label>
												<input type="radio" name="optionsRadios2" value="option1" />
												Free
												</label>
												<label>
												<input type="radio" name="optionsRadios2" value="option2" checked />
												Professional
												</label>
											</div>
										</div>
									</div>
									<div class="form-group">
										<label class="control-label col-md-3">Street</label>
										<div class="col-md-9">
											<input type="text" class="form-control" >
										</div>
									</div>
									<div class="form-group">
										<label class="control-label col-md-3">City</label>
										<div class="col-md-9">
											<input type="text"  class="form-control"> 
										</div>
									</div>
									<div class="form-group">
										<label class="control-label col-md-3">State</label>
										<div class="col-md-9">
											<input type="text"  class="form-control"> 
										</div>
									</div>
									<div class="form-group">
										<label class="control-label col-md-3">Post Code</label>
										<div class="col-md-9">
											<input type="text" class="form-control"> 
										</div>
									</div>
									<div class="form-group last">
										<label class="control-label col-md-3">Country</label>
										<div class="col-md-9">
											<select class="form-control"></select>
										</div>
									</div>
								</div>
								<div class="form-actions fluid">
									<div class="row">
										<div class="col-md-12">
											<div class="col-md-offset-3 col-md-9">
												<button type="submit" class="btn green"><i class="fa fa-check"></i> Submit</button>
												<button type="button" class="btn default">Cancel</button>                              
											</div>
										</div>
									</div>
								</div>
							</form>
							<!-- END FORM-->  
						</div>
					</div>
				</div>
				<div class="tab-pane"  id="tab_7">
					<div class="portlet box blue ">
						<div class="portlet-title">
							<div class="caption"><i class="fa fa-reorder"></i>Form Sample</div>
							<div class="tools">
								<a href="javascript:;" class="collapse"></a>
								<a href="#portlet-config" data-toggle="modal" class="config"></a>
								<a href="javascript:;" class="reload"></a>
								<a href="javascript:;" class="remove"></a>
							</div>
						</div>
						<div class="portlet-body form">
							<!-- BEGIN FORM-->
							<form action="#" class="form-horizontal form-bordered form-label-stripped">
								<div class="form-body">
									<div class="form-group">
										<label class="control-label col-md-3">First Name</label>
										<div class="col-md-9">
											<input type="text" placeholder="small" class="form-control" />
											<span class="help-block">This is inline help</span>
										</div>
									</div>
									<div class="form-group">
										<label class="control-label col-md-3">Last Name</label>
										<div class="col-md-9">
											<input type="text" placeholder="medium" class="form-control" />
											<span class="help-block">This is inline help</span>
										</div>
									</div>
									<div class="form-group">
										<label class="control-label col-md-3">Gender</label>
										<div class="col-md-9">
											<select  class="form-control">
												<option value="">Male</option>
												<option value="">Female</option>
											</select>
											<span class="help-block">Select your gender.</span>
										</div>
									</div>
									<div class="form-group">
										<label class="control-label col-md-3">Date of Birth</label>
										<div class="col-md-9">
											<input type="text" class="form-control"  placeholder="dd/mm/yyyy">
										</div>
									</div>
									<div class="form-group">
										<label class="control-label col-md-3">Category</label>
										<div class="col-md-9">
											<select class="form-control select2_category">
												<option value="Category 1">Category 1</option>
												<option value="Category 2">Category 2</option>
												<option value="Category 3">Category 5</option>
												<option value="Category 4">Category 4</option>
											</select>
										</div>
									</div>
									<div class="form-group">
										<label class="control-label col-md-3">Multi-Value Select</label>
										<div class="col-md-9">
											<select class="form-control select2_sample1" multiple>
												<optgroup label="NFC EAST">
													<option>Dallas Cowboys</option>
													<option>New York Giants</option>
													<option>Philadelphia Eagles</option>
													<option>Washington Redskins</option>
												</optgroup>
												<optgroup label="NFC NORTH">
													<option>Chicago Bears</option>
													<option>Detroit Lions</option>
													<option>Green Bay Packers</option>
													<option>Minnesota Vikings</option>
												</optgroup>
												<optgroup label="NFC SOUTH">
													<option>Atlanta Falcons</option>
													<option>Carolina Panthers</option>
													<option>New Orleans Saints</option>
													<option>Tampa Bay Buccaneers</option>
												</optgroup>
												<optgroup label="NFC WEST">
													<option>Arizona Cardinals</option>
													<option>St. Louis Rams</option>
													<option>San Francisco 49ers</option>
													<option>Seattle Seahawks</option>
												</optgroup>
												<optgroup label="AFC EAST">
													<option>Buffalo Bills</option>
													<option>Miami Dolphins</option>
													<option>New England Patriots</option>
													<option>New York Jets</option>
												</optgroup>
												<optgroup label="AFC NORTH">
													<option>Baltimore Ravens</option>
													<option>Cincinnati Bengals</option>
													<option>Cleveland Browns</option>
													<option>Pittsburgh Steelers</option>
												</optgroup>
												<optgroup label="AFC SOUTH">
													<option>Houston Texans</option>
													<option>Indianapolis Colts</option>
													<option>Jacksonville Jaguars</option>
													<option>Tennessee Titans</option>
												</optgroup>
												<optgroup label="AFC WEST">
													<option>Denver Broncos</option>
													<option>Kansas City Chiefs</option>
													<option>Oakland Raiders</option>
													<option>San Diego Chargers</option>
												</optgroup>
											</select>
										</div>
									</div>
									<div class="form-group">
										<label class="control-label col-md-3">Loading Data</label>
										<div class="col-md-9">
											<input type="hidden" class="form-control select2_sample2">
										</div>
									</div>
									<div class="form-group">
										<label class="control-label col-md-3">Tags Support List</label>
										<div class="col-md-9">
											<input type="hidden" class="form-control select2_sample3" value="red, blue">
										</div>
									</div>
									<div class="form-group">
										<label class="control-label col-md-3">Membership</label>
										<div class="col-md-9">
											<div class="radio-list">                                              
												<label>
												<input type="radio" name="optionsRadios2" value="option1" />
												Free
												</label>
												<label>
												<input type="radio" name="optionsRadios2" value="option2" checked />
												Professional
												</label>  
											</div>
										</div>
									</div>
									<div class="form-group">
										<label class="control-label col-md-3">Street</label>
										<div class="col-md-9">
											<input type="text" class="form-control" >
										</div>
									</div>
									<div class="form-group">
										<label class="control-label col-md-3">City</label>
										<div class="col-md-9">
											<input type="text"  class="form-control"> 
										</div>
									</div>
									<div class="form-group">
										<label class="control-label col-md-3">State</label>
										<div class="col-md-9">
											<input type="text"  class="form-control"> 
										</div>
									</div>
									<div class="form-group">
										<label class="control-label col-md-3">Post Code</label>
										<div class="col-md-9">
											<input type="text" class="form-control"> 
										</div>
									</div>
									<div class="form-group last">
										<label class="control-label col-md-3">Country</label>
										<div class="col-md-9">
											<select  class="form-control"></select>
										</div>
									</div>
								</div>
								<div class="form-actions fluid">
									<div class="row">
										<div class="col-md-12">
											<div class="col-md-offset-3 col-md-9">
												<button type="submit" class="btn green"><i class="fa fa-check"></i> Submit</button>
												<button type="button" class="btn default">Cancel</button>                              
											</div>
										</div>
									</div>
								</div>
							</form>
							<!-- END FORM-->  
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
