<?php 
use Helper\Html;
use Helper\LayoutPart;
?>
<!-- BEGIN PAGE HEADER-->
<div class="row">
	<div class="col-md-12">
		<!-- BEGIN PAGE TITLE & BREADCRUMB-->
		<h3 class="page-title">
			<?=$this->title?> <small><?=$this->brief_desc?></small>
		</h3>
		<?php 
		echo LayoutPart::drawBreadcrumb($this->h_breadcrumb);?>
		<!-- END PAGE TITLE & BREADCRUMB-->
	</div>
</div>
<!-- END PAGE HEADER-->
<!-- BEGIN PAGE CONTENT-->
<div class="row">
	<div class="col-md-12">
		<div class="portlet box green">
			<div class="portlet-title">
				<div class="caption"><i class="fa fa-globe"></i><?=_('服务器信息汇总')?></div>
			</div>
			<div class="portlet-body">
				<table class="table table-striped table-bordered table-hover" id="sample_1">
					<thead>
						<tr>
							<th><?=_('内网IP')?></th>
							<th><?=_('外网IP')?></th>
							<th><?=_('用途')?></th>
							<th><?=_('属主')?></th>
							<th><?=_('当前状态')?></th>
						</tr>
					</thead>
					<tbody>
						
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>
